# Generated by Django 4.2.6 on 2023-11-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurchik', '0003_alter_settings_facebook_alter_settings_instagram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройка'},
        ),
    ]
