# Generated by Django 4.2.6 on 2023-11-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurchik', '0005_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_image/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Введите название')),
                ('descriptions', models.TextField(verbose_name='Введите описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайды', 'verbose_name_plural': 'Слайд'},
        ),
    ]
