# Generated by Django 4.2.6 on 2023-11-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurchik', '0006_about_alter_slide_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_image/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Введите название')),
                ('work', models.CharField(max_length=255, verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
            },
        ),
    ]
