# Generated by Django 4.2.6 on 2023-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurchik', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_image/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Введите название')),
                ('work', models.CharField(max_length=255, verbose_name='Работа')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на инст')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Наши преподователи',
                'verbose_name_plural': 'Наша преподователи',
            },
        ),
    ]
