# Generated by Django 4.2.6 on 2023-11-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurchik', '0008_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Фио')),
                ('work', models.CharField(max_length=255, verbose_name='Специальность')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Наш отзыв',
                'verbose_name_plural': 'Наши отзывы',
            },
        ),
    ]
